# Generated by Django 5.0.4 on 2024-05-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlemodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ('-Created',)},
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='created',
            new_name='Created',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='edited',
            new_name='Edited',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='status',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='slug',
        ),
    ]
