# Generated by Django 5.0.4 on 2024-05-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articlemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='Slug',
            field=models.SlugField(auto_created=True, null=True, unique=True),
        ),
    ]
