# Generated by Django 5.0.6 on 2024-05-19 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_rename_comments_articlecomments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleComments',
            new_name='ArticleCommentsModel',
        ),
    ]
