# Generated by Django 5.0.6 on 2024-05-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_rename_articlecomments_articlecommentsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='slug',
        ),
        migrations.DeleteModel(
            name='ArticleCommentsModel',
        ),
    ]
